### ISSUE TITLE
Prettify Graph Printing | Update to use gographviz's latest API

### ISSUE THREAD

**Issue by chewxy** [gorgonia/gorgonia#103]
Now that [gographviz](https://github.com/awalterschulze/gographviz) has had an update, maybe it's time to actually prettify the code that deals with outputting dotfiles. 

# TODO #
* [x] Fix errors from gographviz
* [ ] Use the new type safe Attrs from gographviz
* [ ] Create new structures for holding the state while writing the dot files

**Comment by owulveryck** [comment]
new encoding package is voiding this issue (see `encoding/dot` package)
