### ISSUE TITLE
Move this to the organization Gorgonia

### ISSUE THREAD

**Issue by chewxy** [gorgonia/gorgonia#98]
This package should be moved to https://github.com/Gorgonia when 1.0 is nearing. This is the result of the thinking that arose from #91.

The purpose of this is to move Gorgonia away from being just a personal project - it's not a personal project since last year, with great contributors like @NDari and @kabaka0 . I'm increasingly worried about the bus factor of this repo. Moving this repo to an organization would allow someone else to step up as main maintainer should you know, I get hit by a bus.

Once the move to the org is done, there are some further things that can be done:

- The `tensor` package should be split out as well. (from `github.com/chewxy/gorgonia/tensor` to `github.com/Gorgonia/tensor`)
- An additional ~~`horny` package (the analogue of Keras)~~ [`golgi`](https://github.com/gorgonia/golgi) package would be added. It's a personal package for now, with a bunch of structs that define a neural network layer, and customized/optimized Ops for convolution, affine (`σ(W×x + bias)`), LSTM and GRU operations.

## TO DO LIST ##

1. [x] Add meta redirect for canonical URL
1. [x] Add canonical URLs: #117 
2. [x] Finish site generation and make sure that the metadata for canonical URLs are added: #80 
3. [x] CNAME file for the gorgonia.org website: https://github.com/Gorgonia/gorgonia.org/issues/1
4. [ ] Write a program to update the gorgonia imports.
4. [x] Move this repo to github.com/gorgonia/gorgonia
5. [x] Move package `cu` to Gorgonia: https://github.com/chewxy/cu/issues/3
6. [x] Move package `vecf64` to Gorgonia: See also #116
7. [x] Move package `vecf32` to Gorgonia: See also #116

**Comment by kabaka0** [comment]
Additional details please?

**Comment by chewxy** [comment]
This package should be moved to https://github.com/Gorgonia when 1.0 is nearing. 

The `tensor` package should be split out as well.

An additional `horny` package (the analogue of Keras) would be added, but I'm in two minds about it because it's quite opinionated -  significantly more so than Keras

**Comment by NDari** [comment]
This may be a side point, but I think before going in that direction, maybe we need to add a bit more.. professionalism to the packages ;) for example, remove all the curse words in the comments, and maybe rename `horny` to something... different. I enjoy the comments, but I think it is worth making this package a bit less colorful since this is a serious package. If this is something we want to do, I can take point on it.

**Comment by damienstanton** [comment]
I'll keep this in mind as I work on the pro-oriented doc site as well.

**Comment by chewxy** [comment]
I agree with @ndari. And `horny` is the name of my personal package that I use personally (it's a reference Keras, which means horn). I mean I get weird looks from people who review my CV and say "you created a package called `sexp`"... 

it'll all be cleaned up

**Comment by NDari** [comment]
Thats not as bad as [sextractor](http://www.astromatic.net/software/sextractor). The name of the binary was `sex`, and if you needed to look up the man page you had to `man sex`.

**Comment by chewxy** [comment]
Updated the main post again, as it's time to start putting some serious work into this issue

**Comment by chewxy** [comment]
Added TODO list as this seems to be a lot more concrete now

**Comment by chewxy** [comment]
Thank you all. @kabaka0 @NDari . This package now lives in the Gorgonia org which you are owners of.
